language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:  test.py
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create schema coin_test;' -U postgres
before_install:
  - sudo apt-get update
  - sudo apt-get install python-requests -y